[project]
authors = ["bobbyely"]
channels = ["conda-forge"]
name = "the-sauce-bottle"
platforms = ["linux-64"]
version = "0.1.0"
description = "Tracking Australian politicians and what they are saying."

[tasks]
# Task to run the FastAPI development server
backend-dev = "uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000"
test-db = "python -m backend.app.db_test"
lint = "ruff check ."
format = "ruff format ."
test = "pytest"
alembic = "alembic"

[dependencies]
python = "3.12.*"
fastapi = ">=0.115.12,<0.116"
pydantic = "*"
pydantic-settings = "*"
asyncpg = "*"
psycopg2-binary = "*"
alembic = "*"
python-dotenv = "*"
pytest = "*"
pytest-asyncio = "*"
httpx = "*"
ruff = "*"
python-multipart = ">=0.0.20,<0.0.21"
uvicorn = ">=0.34.3,<0.35"

[pypi-dependencies]
uvicorn = { version = "*", extras = ["standard"] }
