"""create politician table

Revision ID: b335ac7d5b3f
Revises: 
Create Date: 2025-06-14 23:39:54.175112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b335ac7d5b3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('chamber', sa.String(), nullable=True),
    sa.Column('position_title', sa.String(), nullable=True),
    sa.Column('electorate', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('date_elected', sa.Date(), nullable=True),
    sa.Column('sitting_status', sa.String(), nullable=True),
    sa.Column('is_cabinet_minister', sa.Integer(), nullable=True),
    sa.Column('is_shadow_minister', sa.Integer(), nullable=True),
    sa.Column('previous_positions', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('social_media_links', sa.String(), nullable=True),
    sa.Column('statement_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicians_id'), 'politicians', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_politicians_id'), table_name='politicians')
    op.drop_table('politicians')
    # ### end Alembic commands ###
